config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  #auth
  get "auth/:provider/callback", to: "sessions#google_auth"
  get "auth/failure", to: redirect("/")
  get 'login', to: "sessions#new", as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :projects, only: [:index, :show]
  resources :time_sheets, only: [:create, :index]
  resources :approve_time_sheets, only: [:update, :index]
  resources :adjust_time_sheets, only: [:new, :create, :index]
  resources :cancel_time_sheets, only: [:update]
  resources :users, only: [:show]
  resources :total_hours, only: [:index]
  
  get 'user-time-sheet/:project_id', to: "time_sheets#show"
  put 'user/projects/:project_id/:command', to: "user_projects#update"
  get 'user/:id/profile', to: "user_profiles#show"

  get 'sync-projects', to: "sync_projects#index"
  post 'sync-projects', to: "sync_projects#create"

  namespace :reports do
    resources :allocations, only: [:new, :create]
  end  

  namespace :api do
    
      resources "time_sheets", only: [:index], format: :json do
        collection do
          get "by_user_email_in_period/:email/:start_date/:end_date", action: :by_user_email_in_period, constraints: {:email => /[\w.]+/ }
          get "by_user_email_in_date/:email/:year/:month", action: :by_user_email_in_date, constraints: {:email => /[\w.]+/ }
          get "by_project_gfp/:project_id/:start_date/:end_date", action: :by_project_gfp
          get "all_by_project_gfp/:project_id", action: :all_by_project_gfp
          get "register_time_sheet/:user_email/:gfp_project_id/:hours_spent/:year/:month", action: :register_time_sheet,
           constraints: {:user_email => /[\w.@]+/ }
        end
      end
    

    namespace :v2 do
      get 'hours-worked/:project_id', to: "hours_workeds#index"
    end
  end
  
end

app/controllers/api/time_sheets_controller.rb
module Api
  class TimeSheetsController < Api::ApiController

    def index
      date = Date.today 
      times = TimeSheetModel.where(:month => date.month, :year => date.year)
      render json: times.map { |ts| TimeSheetMapper.new(ts).map }
    end

    def all_by_project_gfp
      begin
        @time_sheets = TimeSheetModel.joins(:project).where("projects.old_gfp_id = ?", params[:project_id])  
        render json: @time_sheets.map { |ts| TimeSheetMapper.new(ts).map }
      rescue ActiveRecord::RecordNotFound
        render json: {error: "No time sheet was found given the identity supplied!"}
      end
    end

    def by_project_gfp
      begin
        @start_date = params[:start_date].to_date.beginning_of_month
        @end_date = params[:end_date].to_date.end_of_month
        @time_sheets = TimeSheetModel.joins(:project).where("projects.old_gfp_id = ?", params[:project_id])
        @time_sheets = @time_sheets.select{|x|
                                            dt = Date.new(x.year, x.month, 1)
                                            dt.between?(@start_date, @end_date)
                                          }
        render json: @time_sheets.map { |ts| TimeSheetMapper.new(ts).map }
      rescue ActiveRecord::RecordNotFound
        render json: {error: "No time sheet was found given the identity supplied!"}
      end
    end

    def register_time_sheet
      user_email = params[:user_email]
      gfp_project_id = params[:gfp_project_id] 
      hours_spent = params[:hours_spent].to_i
      year = params[:year].to_i
      month = params[:month].to_i

      begin
        user = User.find_by_email_without_domain(user_email)
        raise Exception, "User not found" if user.blank?

        project = ProjectModel.find_by_gfp_project_id(gfp_project_id)
        raise Exception, "Project not found" if project.blank?

        unless user.projects.include?(project)
          user.projects << project
          user.save!
          user.reload
        end
        spent_registration = TimeSheets::TimeSpentRegistration.new(user, project, Date.new(year, month, 1))
        time_sheet = spent_registration.register_time_spent!(hours_spent, false)
        spent_registration.send_for_approval!(UserMailer, false)
        render json: {ok: "Time sheet successfully registered!"}
      rescue Exception => e
        render json: {error: e.message} 
      end
    end

    def by_user_email_in_period
      begin
        start_date = params[:start_date].to_date.beginning_of_month
        end_date = params[:end_date].to_date.end_of_month
        user_email = params[:email]

        user = User.find_by_email_without_domain(user_email)
        raise Exception, "User not found" if user.blank?
        time_sheets = TimeSheetModel.where(user_id: user.id)
        time_sheets = user.time_sheets.select{|x|
                                  dt = Date.new(x.year, x.month, 1)
                                  dt.between?(start_date, end_date)
                                }


        render json: time_sheets.map { |ts| TimeSheetMapper.new(ts).map }

      rescue Exception => e
        render json: {error: e.message} 
      end
    end

    def by_user_email_in_date
      begin
        year = params[:year].to_i
        month = params[:month].to_i
        user_email = params[:email]

        user = User.find_by_email_without_domain(user_email)
        raise Exception, "User not found" if user.blank?
        time_sheets = TimeSheetModel.where(user_id: user.id).where(:month => month, :year => year)
        

        render json: time_sheets.map { |ts| TimeSheetMapper.new(ts).map }

      rescue Exception => e
        render json: {error: e.message} 
      end
    end


  end
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController

  def create
    begin
      uc = TimeSheets::UseCases::SaveCurrent.new(user_id: @current_user.id, 
                                        project_id: params[:ts][:project_id], value: params[:ts][:value])
      @ts = uc.execute

      TimeSheets::Services::Notify.new(@ts).exec

    rescue TimeSheets::Exceptions::Invalid => e
      @validation_message = e.message
    rescue Exception => e
      @validation_message = e.message
    end
    
  end

  def show
    begin
      @ts = TimeSheets::Repositories::TimeSheets.new.current_form_user_by_project(user_id: @current_user.id, 
                                                                                project_id: params[:project_id])
      Users::UseCases::UpdateProjects.new(user_id: @current_user.id, project_id: params[:project_id], action:'add').execute
    rescue UserProjectAlreadyExists => e
      @validation_message = e.message
    end
  end
  
end

app/views/time_sheets/status/_approved.html.erb
<div id="project-<%= ts.project.id %>" class="row" data-ts-id="<%= ts.id %>">


<div class="kt-portlet kt-portlet--bordered">
  <div class="kt-portlet__head">
    <div class="kt-portlet__head-label">
      <h3 class="kt-portlet__head-title">
        <%= ts.project.name %>
      </h3>
    </div>
    <div class="kt-portlet__head-toolbar">
        <div class="kt-portlet__head-actions">
            <button type="button" disabled="true" class="btn btn-sm  btn-elevate btn-circle btn-icon">
                <i class="fa fa-check"></i>
            </button>
        </div>
    </div>
  </div>
  <div class="kt-portlet__body">
    <div class="col-lg-11">
    <div class="kt-widget24">
        <div class="kt-widget24__details">
            <div class="kt-widget24__info">
                <h4 class="kt-widget24__title">
                    APROVADO
                </h4>
                <span class="kt-widget24__desc">
                    Por: <%= ts.project.manager.name %>
                </span>
            </div>
            <span class="kt-widget24__stats kt-font-success">
                <div class="text-center text-success" style="font-size: 2rem;" ><i class="fa fa-check"></i></div>
            </span>
        </div>
        <div class="progress progress-lg">
            <div class="progress-bar kt-bg-success" role="progressbar" style="width: <%= ts.percentage %>%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div class="kt-widget24__action">
            <span class="kt-widget24__change">
                <h4><%= ts.hours %> hs</h4>
            </span>
            <span class="kt-widget24__number">
                <h4><%= ts.percentage %>%</h4>
            </span>
        </div>
    </div>
    </div>
   
    
  </div>
</div>

</div>

app/views/time_sheets/status/_reproved.html.erb
<div id="project-<%= ts.project.id %>" class="row item">


<div class="kt-portlet kt-portlet--bordered alert-outline-danger">
  <div class="kt-portlet__head">
    <div class="kt-portlet__head-label">
      <h3 class="kt-portlet__head-title text-danger">
        <%= ts.project.name %>
      </h3>
    </div>
    <div class="kt-portlet__head-toolbar">
        <div class="kt-portlet__head-actions">
            <button type="button" onclick="cancel(<%= ts.id %>,<%= ts.project.id %>);" class="btn btn-sm btn-outline-danger btn-elevate btn-circle btn-icon">
                <i class="la la-close"></i>
            </button>
        </div>
    </div>
  </div>
  <div class="kt-portlet__body">
    <!-- <h4 class="text-center text-danger">RECUSADO</h4> -->

    
    <h5 class="text-danger text-center">RECUSADO <i class="flaticon-warning"></i></h5>

    <%= form_for :ts, url: time_sheets_path, remote: true, class:'kt-form' do |f| %>
        <input type="hidden" name="ts[project_id]" value="<%= ts.project.id %>">
        <h6> Informe o % de horas gastas: </h6>
        <div class="form-group row">
            <div class="col-lg-8 col-md-12 col-sm-12">
                <div class="row align-items-center">
                    <div class="col-3">
                        <input type="text" class="form-control" name="ts[value]" id="value-<%= ts.project.id %>" value="<%= ts.percentage %>" placeholder="%">
                    </div>
                    <div class="col-9">
                        <div id="nouislider-<%= ts.project.id %>" class="kt-nouislider kt-nouislider--handle-danger"></div>
                    </div>
                </div>
                <span class="form-text text-muted mb-2">Arraste a barra ou informe valores múltiplos de 5.</span>
            </div>
            <div class="col-lg-4 col-md-12">
                <button type="submit" data-disable-with="Enviando..." class="btn btn-outline-success float-right">REENVIAR</button>
                <a href="javascript:cancel(<%= ts.id %>,<%= ts.project.id %>)" class="btn btn-outline-danger float-right mr-3">
                    CANCELAR
                </a>
            </div>
        </div>

    <% end %>
    
  </div>
</div>

</div>

app/views/time_sheets/status/_waiting-approval.html.erb
<div id="project-<%= ts.project.id %>" class="row" data-ts-id="<%= ts.id %>">


<div class="kt-portlet kt-portlet--bordered">
  <div class="kt-portlet__head">
    <div class="kt-portlet__head-label">
      <h3 class="kt-portlet__head-title">
        <%= ts.project.name %>
      </h3>
    </div>
    <div class="kt-portlet__head-toolbar">
        <div class="kt-portlet__head-actions">
            <button type="button" disabled="true" class="btn btn-sm  btn-elevate btn-circle btn-icon">
                <i class="fa fa-history"></i>
            </button>
        </div>
    </div>
  </div>
  <div class="kt-portlet__body">
    
    <%# form_for :ts, url: time_sheets_path, remote: true, class:'kt-form' do |f| %>
        <input type="hidden" name="ts[project_id]" value="<%= ts.project.id %>">
        <h5 class="text-dark">% de horas gastas: </h5>
        <div class="form-group row">
            <div class="col-lg-10 col-md-12 col-sm-12">
                <div class="row align-items-center">
                    <div class="col-3">
                        <input type="text" disabled="true" class="form-control" name="ts[value]" id="value-<%= ts.project.id %>" value="<%= ts.percentage %>" placeholder="%">
                    </div>
                    <div class="col-7">
                        <div id="nouislider-<%= ts.project.id %>" class="kt-nouislider kt-nouislider--handle-danger"></div>
                    </div>
                </div>
                <span class="form-text text-dark mb-2">Alocação aguardando aprovação do gestor do projeto.</span>
            </div>
            <div class="col-lg-2 col-md-12">

                <div class="alert-secondary p-2" role="alert">
                    <div class="text-center" style="font-size: 1.2rem;" ><i class="fa fa-history"></i></div>
                    <h6 class="text-center">Aguardando aprovação</h6>
                </div>
                <!-- <button type="submit" class="btn btn-outline-success float-right">ENVIAR</button> -->
            </div>
        </div>

    <%# end %>
    
  </div>
</div>

</div>