config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  #auth
  get "auth/:provider/callback", to: "sessions#google_auth"
  get "auth/failure", to: redirect("/")
  get 'login', to: "sessions#new", as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :projects, only: [:index, :show]
  resources :time_sheets, only: [:create, :index]
  resources :approve_time_sheets, only: [:update, :index]
  resources :adjust_time_sheets, only: [:new, :create, :index]
  resources :cancel_time_sheets, only: [:update]
  resources :users, only: [:show]
  resources :total_hours, only: [:index]
  
  get 'user-time-sheet/:project_id', to: "time_sheets#show"
  put 'user/projects/:project_id/:command', to: "user_projects#update"
  get 'user/:id/profile', to: "user_profiles#show"

  get 'sync-projects', to: "sync_projects#index"
  post 'sync-projects', to: "sync_projects#create"

  namespace :reports do
    resources :allocations, only: [:new, :create]
  end  

  namespace :api do
    
      resources "time_sheets", only: [:index], format: :json do
        collection do
          get "by_user_email_in_period/:email/:start_date/:end_date", action: :by_user_email_in_period, constraints: {:email => /[\w.]+/ }
          get "by_user_email_in_date/:email/:year/:month", action: :by_user_email_in_date, constraints: {:email => /[\w.]+/ }
          get "by_project_gfp/:project_id/:start_date/:end_date", action: :by_project_gfp
          get "all_by_project_gfp/:project_id", action: :all_by_project_gfp
          get "register_time_sheet/:user_email/:gfp_project_id/:hours_spent/:year/:month", action: :register_time_sheet,
           constraints: {:user_email => /[\w.@]+/ }
        end
      end
    

    namespace :v2 do
      get 'hours-worked/:project_id', to: "hours_workeds#index"
    end
  end
  
end

app/controllers/adjust_time_sheets_controller.rb
class AdjustTimeSheetsController < ApplicationController

  def index
    date = Date.today - 1.month
    year = params[:year] || date.year 
    month = params[:month] || date.month
    @current_date = "#{month}/#{year}"
    rep = TimeSheets::Repositories::TimeSheets.new
    @data = rep.times_sheets_aprroveds_by_user_and_date(user_id: @current_user.id, month: month, year: year)
    @dates = rep.time_sheets_dates_aprroveds_by_user(user_id: @current_user.id).map { |dt| "#{dt.month}/#{dt.year}" }
  end

  def new
    @ts = TimeSheets::Repositories::TimeSheets.new.get_or_new(params[:id])
    @projects = Projects::Repositories::Projects.new.by_responsible(@current_user)
    @users = User.order(:name).map { |user| UserPresenter.new(user) }
    @form = FormPresenter.new
  end

  def create
    begin
      date = Date.strptime("1/#{params[:ts][:date]}",'%d/%m/%y')
      year =  date.year
      month = date.month
      id = params[:id] if params[:id] != ""
      uc = TimeSheets::UseCases::Adjust.new(id: id, user_id: params[:ts][:user_id], project_id: params[:ts][:project_id], 
                                          value: params[:ts][:value], month: month, year: year)
      @ts = uc.execute
      
      TimeSheets::Services::Notify.new(@ts).exec

      flash[:notice] = "Adequação de horas realizada"
      redirect_to root_path
    rescue Exception => e
      flash[:notice] = e.message
      redirect_to new_adjust_time_sheet_path({id: params[:id]})
    end
  end
  
end

app/views/adjust_time_sheets/_ts.html.erb
<div class="kt-portlet kt-portlet--bordered">
  <div class="kt-portlet__head">
    <div class="kt-portlet__head-label">
      <h3 class="kt-portlet__head-title">
        <%= ts.project.name %>
      </h3>
    </div>
    <div class="kt-portlet__head-toolbar">
    </div>
  </div>
  <div class="kt-portlet__body">

      <div class="kt-widget4">
        <% ts.time_sheets.each do |ts| %>
        <div id="ts-<%= ts.id %>" class="kt-widget4__item">
          <div class="person-pic mb-4 pb-4 mr-1">
            <img src="<%= asset_path('avatar-placeholder.png') %>" class="user-avatar" data-user="<%= ts.user.id %>" alt="">
          </div>
          <div class="kt-widget4__info">
            <div class="kt-widget4__username">
              <div class="col-xl-10">
                <h5 class="text-info"><%= ts.user.name %></h5>
                <h5><%= ts.project.name %></h5>
              </div>
            </div>
            <p class="kt-widget4__text">
              <div class="col-xl-5">
                <h6><%= ts.hours %> horas executadas  <small>- <%= ts.percentage %>%</small></h6>
                <div class="row">
                  <div class="col-xl-10">
                    <div class="progress progress-sm">
                      <div class="progress-bar bg-brand" role="progressbar" style="width: <%= ts.percentage %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
            </p>
          </div>
          <button class="btn btn-sm btn-label-danger btn-bold btn-disapprove" data-id="<%= ts.id %>" >
            RECUSAR
          </button>
        </div>
        <% end %>
      </div>

  </div>
</div>

app/views/adjust_time_sheets/index.html.erb
<div class="col-xl-8 col-md-12">
  <div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
        <h3 class="kt-portlet__head-title">
          Acompanhamento de alocações
        </h3>
      </div>

      <div class="kt-portlet__head-toolbar">
        <div class="kt-portlet__head-actions">
          <a href="<%= root_path %>" class="btn btn-sm btn-outline-info btn-elevate btn-circle btn-icon">
              <i class="la la-close"></i>
          </a>
        </div>
      </div>

    </div>
  <div class="kt-portlet__body">

    <div class="row">
      <div class="col-md-12">
        <div class="kt-scroll mb-3" data-scroll-x="true" data-scroll="true">
          <div style="width: <%= 100 * @dates.count %>px">
            <% @dates.each do |dt| %>
              <a href="<%= adjust_time_sheets_path({month: dt.split('/')[0], year: dt.split('/')[1]}) %>" class="btn btn-outline-info btn-sm btn-date <%= 'active' if dt == @current_date %> ">
                <%= dt %>
              </a>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
      <%= render partial: 'adjust_time_sheets/ts', collection: @data %>
      </div>
    </div>

   </div>
  </div>
</div>



<% content_for :javascript do %>
  <%= javascript_include_tag 'app/adjust_ts/index.js', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/adjust_time_sheets/new.html.erb
<div class="row">

  <div class="d-md-none d-lg-block col-xl-3"></div>

  <div class="ml-1 col-xl-6 col-md-12 mr-1 mb-4">

    <div class="col-12 pr-3 pl-3">


        <div id="ts-<%= @ts.id || 0 %>" class="row">


        <div class="kt-portlet kt-portlet--bordered">
          <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
              <h3 class="kt-portlet__head-title mr-1">
               Adequar horas 
              </h3>
            </div>

            <div class="kt-portlet__head-toolbar">
              <div class="kt-portlet__head-actions">
                <a href="<%= root_path %>" class="btn btn-sm btn-outline-info btn-elevate btn-circle btn-icon">
                    <i class="la la-close"></i>
                </a>
            </div>
          </div>

          </div>
          <div class="kt-portlet__body">
            
            <%= form_for :ts, url: adjust_time_sheets_path, html: {id:'form-ts', class:'kt-form'} do |f| %>
                <input type="hidden" name="id" value="<%= @ts.id %>">
                <div class="form-group row">
                  <div class="col-lg-10 col-md-12 col-sm-12">
                  <label>Projeto:</label>
                  <select class="form-control m-select2" id="ts_project_id" <%= @form.required %> name="ts[project_id]">
                    <option value="">Selecione...</option>
                    <%= @form.options_for_select(@projects,@ts.project_id) %>
                  </select>
                  <div class="help-block with-errors text-danger"></div>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-lg-10 col-md-12 col-sm-12">
                  <label>Colaborador:</label>
                  <select class="form-control m-select2" id="ts_user_id" <%= @form.required %> name="ts[user_id]">
                    <option value="">Selecione...</option>
                    <%= @form.options_for_select(@users,@ts.user_id) %>
                  </select>
                  <div class="help-block with-errors text-danger"></div>
                  </div>
                </div>

                
                <div class="form-group row">
                  <div class="col-lg-2 col-md-6 col-sm-6">
                    <label>Mês/Ano:</label>
                    <input type="text" class="form-control month-year-mask-short" placeholder="DD/AA" <%= @form.required %> name="ts[date]" value='<%= "#{@ts.month}/#{@ts.year.to_s[2..3]}" if @ts.month %>'>
                    <div class="help-block with-errors text-danger"></div>
                  </div>
                </div>

                <h6 class="text-dark"> Informe o % de horas gastas: </h6>
                <div class="form-group row">
                    <div class="col-lg-10 col-md-12 col-sm-12">
                        <div class="row align-items-center">
                            <div class="col-3">
                                <input type="text" class="form-control" name="ts[value]" <%= @form.required %> id="value-<%= @ts.id || 0 %>" value="<%= @ts.percentage %>" placeholder="%">
                            </div>
                            <div class="col-7">
                                <div id="nouislider-<%= @ts.id || 0 %>" class="kt-nouislider kt-nouislider--handle-danger"></div>
                            </div>
                        </div>
                        <div class="help-block with-errors text-danger"></div>
                        <span class="form-text text-dark mb-2">Arraste a barra ou informe valores múltiplos de 5.</span>
                    </div>
                    <div class="col-lg-2 col-md-12">
                        <button type="submit" class="btn btn-outline-success float-right">ENVIAR</button>
                    </div>
                </div>

            <% end %>
            
          </div>
        </div>

        </div>




      </div>
  </div>
</div>


<% content_for :javascript do %>
  <%= javascript_include_tag 'vendors/validator.js'  %>
  <%= javascript_include_tag 'vendors/nouislider/distribute/nouislider.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'app/adjust_ts/new.js', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript">
    
    jQuery(document).ready(function() {
       slider(<%= @ts.id || 0 %>,<%= @ts.percentage.to_i %>);
    });
  </script>
<% end %>