config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  #auth
  get "auth/:provider/callback", to: "sessions#google_auth"
  get "auth/failure", to: redirect("/")
  get 'login', to: "sessions#new", as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :projects, only: [:index, :show]
  resources :time_sheets, only: [:create, :index]
  resources :approve_time_sheets, only: [:update, :index]
  resources :adjust_time_sheets, only: [:new, :create, :index]
  resources :cancel_time_sheets, only: [:update]
  resources :users, only: [:show]
  resources :total_hours, only: [:index]
  
  get 'user-time-sheet/:project_id', to: "time_sheets#show"
  put 'user/projects/:project_id/:command', to: "user_projects#update"
  get 'user/:id/profile', to: "user_profiles#show"

  get 'sync-projects', to: "sync_projects#index"
  post 'sync-projects', to: "sync_projects#create"

  namespace :reports do
    resources :allocations, only: [:new, :create]
  end  

  namespace :api do
    
      resources "time_sheets", only: [:index], format: :json do
        collection do
          get "by_user_email_in_period/:email/:start_date/:end_date", action: :by_user_email_in_period, constraints: {:email => /[\w.]+/ }
          get "by_user_email_in_date/:email/:year/:month", action: :by_user_email_in_date, constraints: {:email => /[\w.]+/ }
          get "by_project_gfp/:project_id/:start_date/:end_date", action: :by_project_gfp
          get "all_by_project_gfp/:project_id", action: :all_by_project_gfp
          get "register_time_sheet/:user_email/:gfp_project_id/:hours_spent/:year/:month", action: :register_time_sheet,
           constraints: {:user_email => /[\w.@]+/ }
        end
      end
    

    namespace :v2 do
      get 'hours-worked/:project_id', to: "hours_workeds#index"
    end
  end
  
end

app/views/layouts/_header.html.erb
<!-- begin:: Header -->
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed desktop" data-ktheader-minimize="on">
  <div class="kt-header__top">
      <div class="kt-container">

        <!-- begin:: Brand -->
        <div class="kt-header__brand   kt-grid__item" id="kt_header_brand">
          <div class="kt-header__brand-logo">
            <a href="<%= root_path %>">
              <img alt="Logo" src="<%= asset_path 'logo_header.png' %>" height="33px;"  class="kt-header__brand-logo-default" />
            </a>
          </div>
        </div>

        <!-- end:: Brand -->

        <!-- begin:: Header Topbar -->
        <div class="kt-header__topbar kt-grid__item kt-grid__item--fluid hidden-xs hidden-sm">

          <!--begin: User bar -->
          <div class="kt-header__topbar-item kt-header__topbar-item--user hidden-xs hidden-sm">
            <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
              <span class="kt-header__topbar-welcome">Olá,</span>
              <span class="kt-header__topbar-username <%= @current_user.id %>"><%= @current_user.first_name %></span>
              <img class="kt-hidden-xs" alt="<%= @current_user.first_name %>" src="<%= @current_user.avatar || asset_path('avatar-placeholder.png') %>" />
              <span class="kt-header__topbar-icon kt-header__topbar-icon--brand kt-hidden">
                <b><%= @current_user.first_name[0] %></b>
              </span>
            </div>
            <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-xl">

              <!--begin: Head -->
              <div class="kt-user-card kt-user-card--skin-light kt-notification-item-padding-x">
                <div class="kt-user-card__avatar">
                  <img class="kt-hidden-" alt="<%= @current_user.first_name %>" src="<%= @current_user.avatar || asset_path('avatar-placeholder.png') %>" />

                  <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                  <span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold kt-hidden"><%= @current_user.first_name[0] %></span>
                </div>
                <div class="kt-user-card__name">
                  <%= @current_user.name %>
                </div>
                
              </div>

              <!--end: Head -->

              <!--begin: Navigation -->
              <div class="kt-notification">
                <% if @current_user.is_admin? %>
                <a href="<%= new_adjust_time_sheet_path %>" class="kt-notification__item">
                  <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                      Adequação de horas
                    </div>
                  </div>
                </a>

                <a href="<%= new_reports_allocation_path %>" class="kt-notification__item">
                  <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                      Relatório
                    </div>
                  </div>
                </a>

                <a href="<%= sync_projects_path %>" class="kt-notification__item">
                  <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                      Sincronizar projetos
                    </div>
                  </div>
                </a>
                <% end %>

                
                

                <div class="kt-notification__custom">
                  <%= link_to "Sair", logout_path, method: :delete, class: "btn btn-label-brand btn-sm btn-bold" %>
                </div>
              </div>

              <!--end: Navigation -->
            </div>
          </div>

          <!--end: User bar -->
        </div>

        <!-- end:: Header Topbar -->
      </div>
  </div>
</div>
<!-- end:: Header -->

app/views/layouts/_header_mobile.html.erb
    <!-- begin:: Header Mobile -->
    <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
      <div class="kt-header-mobile__logo">
        <a href="<%= root_path %>">
          <img alt="Logo" src="<%= asset_path 'logo_header.png' %>" height="20px;" />
        </a>
      </div>
      <div class="kt-header-mobile__toolbar">
                  <!--begin: User bar -->
          <div class="kt-header__topbar-item kt-header__topbar-item--user">
            <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
              <% if @current_user.avatar %>
                <img class="kt-hidden-" alt="<%= @current_user.first_name %>" src="<%= @current_user.avatar %>" width="40px" style ="border-radius:5px;" />
              <% else %>
                  <span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold"><%= @current_user.first_name[0] %></span>
              <% end %>
              <span class="kt-header__topbar-icon kt-header__topbar-icon--brand kt-hidden">
                <b><%= @current_user.first_name[0] %></b>
              </span>
            </div>
            <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-xl">

              <!--begin: Head -->
              <div class="kt-user-card kt-user-card--skin-light kt-notification-item-padding-x">
                <div class="kt-user-card__avatar">
                  <% if @current_user.avatar %>
                  <img class="kt-hidden-" alt="<%= @current_user.first_name %>" src="<%= @current_user.avatar %>" />
                  <% else %>
                  <span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold"><%= @current_user.first_name[0] %></span>
                  <% end %>
                </div>
                <div class="kt-user-card__name">
                  <%= @current_user.name %>
                </div>
                
              </div>

              <!--end: Head -->

              <!--begin: Navigation -->
              <div class="kt-notification">
                <a href="<%# edit_profile_path %>" class="kt-notification__item">
                  <div class="kt-notification__item-icon">
                    <i class="flaticon2-calendar-3 kt-font-success"></i>
                  </div>
                  <div class="kt-notification__item-details">
                    <div class="kt-notification__item-title kt-font-bold">
                      Meu perfil
                    </div>
                    
                  </div>
                </a>
                

                <div class="kt-notification__custom">
                  <%= link_to "Sair", logout_path, method: :delete, class: "btn btn-label-brand btn-sm btn-bold" %>
                </div>
              </div>

              <!--end: Navigation -->
            </div>
          </div>

          <!--end: User bar -->
        <!-- <button class="kt-header-mobile__toolbar-toggler" id="kt_header_mobile_toggler"><span></span></button> -->
        <!-- <button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more-1"></i></button> -->
      </div>
    </div>
    <!-- end:: Header Mobile -->

app/views/layouts/_top_bar.html.erb
              <!-- BEGIN: Topbar -->
              <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
                <div class="m-stack__item m-topbar__nav-wrapper">
                  <ul class="m-topbar__nav m-nav m-nav--inline">


                    <%# "Olá #{@current_user.name}, #{@current_user.email}" if @current_user %>
                    <% if @current_user %> 
                    <li class="m-nav__item m-dropdown m-dropdown--medium m-dropdown--arrow  m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light" m-dropdown-toggle="click">
                      <a href="#" class="m-nav__link m-dropdown__toggle">
                        <span class="m-topbar__username m--hidden-mobile text-secondary" style="font-size: 14px;">
                          <i class="fa fa-user mr-2"></i> <strong><%# @current_user.first_name %></strong>
                        </span>
                        <span class="m-topbar__userpic">
                          <img src="assets/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless m--img-centered" alt="" />
                        </span>
                        <span class="m-nav__link-icon m-topbar__usericon  m--hide">
                          <span class="m-nav__link-icon-wrapper"><i class="flaticon-user-ok"></i></span>
                        </span>
                      </a>
                      <div class="m-dropdown__wrapper">
                        <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                        <div class="m-dropdown__inner">
                          <div class="m-dropdown__header m--align-center">
                            <div class="m-card-user m-card-user--skin-light">
                              <div class="m-card-user__pic">
                                <img src="assets/app/media/img/users/user4.jpg" class="m--img-rounded m--marginless" alt="" />
                              </div>
                              <div class="m-card-user__details">
                                <span class="m-card-user__name m--font-weight-500"><%# @current_user.name %></span>
                                <a href="" class="m-card-user__email m--font-weight-300 m-link"><%# @current_user.email %></a>
                              </div>
                            </div>
                          </div>
                          <div class="m-dropdown__body">
                            <div class="m-dropdown__content">
                              <ul class="m-nav m-nav--skin-light">
                                <li class="m-nav__section m--hide">
                                  <span class="m-nav__section-text">Section</span>
                                </li>
                                <!-- <li class="m-nav__item">
                                  <a href="profile.html" class="m-nav__link">
                                    <i class="m-nav__link-icon flaticon-profile-1"></i>
                                    <span class="m-nav__link-title">
                                      <span class="m-nav__link-wrap">
                                        <span class="m-nav__link-text">My Profile</span>
                                        <span class="m-nav__link-badge"><span class="m-badge m-badge--success">2</span></span>
                                      </span>
                                    </span>
                                  </a>
                                </li> -->
                                
                                <li class="m-nav__separator m-nav__separator--fit">
                                </li>
                                <li class="m-nav__item">
                                  <%= link_to "Sair", 'logout_path', method: :delete, class: "btn m-btn--pill btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder" %>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                    <% end %>




                  </ul>
                </div>
              </div>

              <!-- END: Topbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

  <!-- begin::Head -->
  <head>
    <meta charset="utf-8" />
    <title>TIMESHEET - E L O G R O U P</title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
      WebFont.load({
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700","Asap+Condensed:500"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
        </script>

    <!--end::Web font -->
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--end:: Global Mandatory Vendors -->
    <!--begin:: Global Optional Vendors -->
    <%# stylesheet_link_tag 'vendors/vendors-bundle', media: 'all','data-turbolinks-track': 'reload' %>
    <!--end:: Global Optional Vendors -->


    <!--begin::Global Theme Styles -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
<!--     <link href="assets/demo/base/style.bundle.css" rel="stylesheet" type="text/css" /> -->

    <!--RTL version:<link href="assets/demo/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

    <!--end::Global Theme Styles -->

    <!--RTL version:<link href="assets/vendors/custom/fullcalendar/fullcalendar.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

    <!--end::Page Vendors Styles -->
    <link rel="shortcut icon" href="<%= asset_path 'favicon.png' %>" />
    <%= csrf_meta_tag %>
  </head>

  <!-- end::Head -->


  <!-- LAYOUT -->
  <!-- begin::Body -->
  <body class="kt-page--fluid kt-page-content-white kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-page--loading">

    <%= render partial: 'layouts/header_mobile' %>


    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
      <div class="kt-subheader__main">
        <%= yield :subheader %>
      </div>
    </div>

    

    <!-- begin:: Page -->

    <div class="kt-grid kt-grid--hor kt-grid--root">
      <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper " id="kt_wrapper">

          <%= render partial: 'layouts/header' %>


          <%= render partial: 'shared/flash' %>

          <!-- begin:: Content -->
          <div class="kt-content kt-grid__item kt-grid__item--fluid">
            <%= yield %>
          </div>
          <!-- end:: Content -->

        </div>


          <!-- begin:: Footer -->
          
          <!-- end:: Footer -->



      </div>
    </div>





  <!-- end::Body -->
  <!-- LAYOUT -->

  

    <!-- end::Scroll Top -->
    <input type="hidden" id="current-date" value="<%= l Date.today %>">

    <!--begin:: Global Mandatory Vendors -->
    <%= javascript_include_tag 'layout/mandatory_vendors', 'data-turbolinks-track': 'reload' %>
    <!--end:: Global Mandatory Vendors -->

    <!--begin:: Global Optional Vendors -->
    <%= yield :javascript %>
    <!--end:: Global Optional Vendors -->
  
    <!--begin::Global Theme Bundle -->
    <%= javascript_include_tag 'layout/scripts.bundle', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag 'layout/app.bundle', 'data-turbolinks-track': 'reload' %>
    <!--end::Global Theme Bundle -->


    <!-- begin::Global Config(global config for global JS sciprts) -->
    <script>
      var KTAppOptions = {
        "colors": {
          "state": {
            "brand": "#5d78ff",
            "light": "#ffffff",
            "dark": "#282a3c",
            "primary": "#5867dd",
            "success": "#34bfa3",
            "info": "#36a3f7",
            "warning": "#ffb822",
            "danger": "#fd3995"
          },
          "base": {
            "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
            "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
          }
        }
      };
    </script>


    <!--end::Page Vendors -->

    

    <!-- begin::Page Loader -->
    <script>
      $(window).on('load', function() {
        $('body').removeClass('m-page--loading');
      });

      <% if @enable_ajax_block %>
      $(document).ajaxStart(ajaxStart).ajaxStop(ajaxStop);
      <% end %>
    </script>



    <!-- end::Page Loader -->

    <%= yield :modals %>
  </body>

  <!-- end::Body -->
</html>